name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit

    - name: Run Bandit (SAST)
      continue-on-error: false
      run: bandit -r .

    - name: Build Docker image
      run: |
        ls -l  # Debug: list files in current dir
        docker build -t python-app:latest .
      working-directory: ${{ github.workspace }}

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'python-app:latest'

