name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit

    - name: Run Bandit (SAST)
      continue-on-error: false
      run: bandit -r .

    # - name: Build Docker image
    #   run: |
    #     ls -l  # Debug: list files in current dir
    #     docker build -t adamlor/adam-python:latest .
    #     docker image ls
    #     docker login -u adamlor -p ${{ secrets.DOCKER_PASSWORD }}
    #     docker push adamlor/adam-python:latest

    - name: Set TAG env variable
      id: vars
      run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
    - name: Build Docker Image with Tags
      run: |
        # TAG=$(git rev-parse --short HEAD)
        docker build -t adamlor/adam-python:$TAG .
        docker image ls
   

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      continue-on-error: false
      with:
        image-ref: 'adamlor/adam-python:${{ env.TAG }}'

    - name: Push Docker Image with Tags
      run: |
        docker login -u adamlor -p ${{ secrets.DOCKER_PASSWORD }}
        docker push adamlor/adam-python:${{ env.TAG }}     
